apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: custom-mlp-psp
spec:
  privileged: false
  runAsUser:
    rule: MustRunAs
    ranges:
    - min: 1000
      max: 2000
  seLinux:
    rule: RunAsAny
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 5000
      max: 6000
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 5000
      max: 6000
  volumes:
  - 'secret'
  - 'emptyDir'
