---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-mlp-psp
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["mlp-psp"]
    verbs: ["use"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-mlp-psp
subjects:
  - kind: ServiceAccount
    name: mlp-sa
    namespace: mlp-ns
roleRef:
  kind: Role
  name: use-mlp-psp
  apiGroup: rbac.authorization.k8s.io
  